In [1]:
#importing library
import pandas as pd

In [2]:
#we convert the excel document to a dataframe 
df = pd.read_excel("corporate.xlsx")

In [3]:
#we are just logging to see how the file looks like after conversion
df

,Timestamp,1. Firm Type,Age,Gender,Highest Qualification,Years of Service,Environment [This firm practices recycling pollutants and wastes.],Environment [This firm manufactures eco-friendly products.],Environment [This firm purchases environmentally friendly products.],Environment [This firm voluntarily does recycling and re-use.],...,Innovation [Our new product introduction has increased],Firm Reputation [The firm has a good reputation in the industry.],Firm Reputation [The firm is known for its high-quality products/services],Firm Reputation [The firm is reliable and trustworthy.],Firm Reputation [The firm has a positive image among its stakeholders.],Firm Reputation [The firm is respected and admired by its competitors.],Financial Performance [We had larger market share],Financial Performance [Our sales growth has been substantially better.],Financial Performance [Return on assets has been substantially better.],Financial Performance [Return on investment has been substantially.]
0,2023-04-10 17:08:11.946,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-04-10 18:26:23.983,Small,30-39,Male,Master’s Degree,1-5 years,A,A,A,A,...,A,A,A,A,A,A,A,A,A,A
2,2023-04-10 18:59:25.076,Medium,20-29,Male,Bachelor Degree,1-5 years,N,D,N,N,...,N,N,N,N,N,N,N,N,N,N
3,2023-04-10 19:20:21.946,Medium,20-29,Female,Master’s Degree,1-5 years,N,N,A,D,...,A,A,A,A,A,A,A,A,A,A
4,2023-04-10 19:20:29.145,Small,20-29,Male,Bachelor Degree,1-5 years,N,N,N,N,...,A,A,A,A,A,A,A,A,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,2023-05-21 15:15:28.668,Small,30-39,Male,Master’s Degree,6-10 years,D,A,A,D,...,A,A,A,A,A,A,A,A,A,A
247,2023-05-21 15:16:49.891,Big,40-49,Male,Master’s Degree,11-15 years,A,A,A,A,...,A,A,A,A,A,A,A,A,A,A
248,2023-05-21 15:18:39.230,Big,30-39,Male,Bachelor Degree,6-10 years,D,A,A,D,...,A,A,A,A,A,A,A,A,A,A
249,2023-05-28 21:40:57.415,Medium,40-49,Female,Master’s Degree,11-15 years,A,A,A,A,...,A,A,A,A,A,A,A,A,A,A
250,2023-05-28 21:42:01.498,Big,30-39,Male,Master’s Degree,11-15 years,A,A,A,A,...,A,A,A,A,A,A,A,A,A,A

The are a number of methods that can be used but i will use the replace method

- I will demonstrate replacing each column one after the other
- I will demonstrate replacing it all at onces

In [4]:
#replacing all the values with D, N, A with the numbers. This replaces it in every column with those values
df2 = df.replace({'D': 1, 'N': 2, 'A': 3})

In [5]:
#this is the results
df2

,Timestamp,1. Firm Type,Age,Gender,Highest Qualification,Years of Service,Environment [This firm practices recycling pollutants and wastes.],Environment [This firm manufactures eco-friendly products.],Environment [This firm purchases environmentally friendly products.],Environment [This firm voluntarily does recycling and re-use.],...,Innovation [Our new product introduction has increased],Firm Reputation [The firm has a good reputation in the industry.],Firm Reputation [The firm is known for its high-quality products/services],Firm Reputation [The firm is reliable and trustworthy.],Firm Reputation [The firm has a positive image among its stakeholders.],Firm Reputation [The firm is respected and admired by its competitors.],Financial Performance [We had larger market share],Financial Performance [Our sales growth has been substantially better.],Financial Performance [Return on assets has been substantially better.],Financial Performance [Return on investment has been substantially.]
0,2023-04-10 17:08:11.946,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-04-10 18:26:23.983,Small,30-39,Male,Master’s Degree,1-5 years,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
2,2023-04-10 18:59:25.076,Medium,20-29,Male,Bachelor Degree,1-5 years,2.0,1.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
3,2023-04-10 19:20:21.946,Medium,20-29,Female,Master’s Degree,1-5 years,2.0,2.0,3.0,1.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
4,2023-04-10 19:20:29.145,Small,20-29,Male,Bachelor Degree,1-5 years,2.0,2.0,2.0,2.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,2023-05-21 15:15:28.668,Small,30-39,Male,Master’s Degree,6-10 years,1.0,3.0,3.0,1.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
247,2023-05-21 15:16:49.891,Big,40-49,Male,Master’s Degree,11-15 years,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
248,2023-05-21 15:18:39.230,Big,30-39,Male,Bachelor Degree,6-10 years,1.0,3.0,3.0,1.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
249,2023-05-28 21:40:57.415,Medium,40-49,Female,Master’s Degree,11-15 years,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
250,2023-05-28 21:42:01.498,Big,30-39,Male,Master’s Degree,11-15 years,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0

In [8]:
#This gives me all the column titles of the file.
df2.columns

Index(['Timestamp', '1.     Firm Type', 'Age', 'Gender',
       'Highest Qualification', 'Years of Service',
       'Environment [This firm practices recycling pollutants and wastes.]',
       'Environment [This firm manufactures eco-friendly products.]',
       'Environment [This firm purchases environmentally friendly products.]',
       'Environment [This firm voluntarily does recycling and re-use.]',
       'Economic  [This firm has a strong competitive position.]',
       'Economic  [This firm seeks a profitable business.]',
       'Economic  [This firm closely monitor employees' productivity.]',
       'Economic  [This firm maximizing our profits]',
       'Social  [This firm supports culture and art activities]',
       'Social  [This firm participate in charitable activities]',
       'Social  [This firm supports educational institutions.]',
       'Social  [This firm assists to enhance quality of life]',
       'Legal  [This firm obeys state, and local regulations.]',
       'Legal  [This firm fulfills its legal obligation.]',
       'Legal  [This firm meets minimal legal requirements]',
       'Legal  [Our products meet legal standards]',
       'Innovation [This firm frequently tries out new ideas]',
       'Innovation [This firm seeks out new ways to do things.]',
       'Innovation [Our company is creative]',
       'Innovation [Our new product introduction has increased]',
       'Firm Reputation  [The firm has a good reputation in the industry.]',
       'Firm Reputation  [The firm is known for its high-quality products/services]',
       'Firm Reputation  [The firm is reliable and trustworthy.]',
       'Firm Reputation  [The firm has a positive image among its stakeholders.]',
       'Firm Reputation  [The firm is respected and admired by its competitors.]',
       'Financial Performance  [We had larger market share]',
       'Financial Performance  [Our sales growth has been substantially better.]',
       'Financial Performance  [Return on assets has been substantially better.]',
       'Financial Performance  [Return on investment has been substantially.]'],
      dtype='object')

In [9]:
#i want to find the uniques values of this column. I will then assign the numerical values
df2['Highest Qualification'].unique()

array([nan, 'Master’s Degree', 'Bachelor Degree', 'PHD', 'Diploma',
       'Certificate'], dtype=object)

In [10]:
# i will replace each value with their corresponding numerical value
df3 = df2.replace({'Certificate': 1, 'Diploma': 2, 'Bachelor Degree': 3, 'Master’s Degree': 4, 'PHD': 5})

In [11]:
#the results
df3

,Timestamp,1. Firm Type,Age,Gender,Highest Qualification,Years of Service,Environment [This firm practices recycling pollutants and wastes.],Environment [This firm manufactures eco-friendly products.],Environment [This firm purchases environmentally friendly products.],Environment [This firm voluntarily does recycling and re-use.],...,Innovation [Our new product introduction has increased],Firm Reputation [The firm has a good reputation in the industry.],Firm Reputation [The firm is known for its high-quality products/services],Firm Reputation [The firm is reliable and trustworthy.],Firm Reputation [The firm has a positive image among its stakeholders.],Firm Reputation [The firm is respected and admired by its competitors.],Financial Performance [We had larger market share],Financial Performance [Our sales growth has been substantially better.],Financial Performance [Return on assets has been substantially better.],Financial Performance [Return on investment has been substantially.]
0,2023-04-10 17:08:11.946,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-04-10 18:26:23.983,Small,30-39,Male,4.0,1-5 years,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
2,2023-04-10 18:59:25.076,Medium,20-29,Male,3.0,1-5 years,2.0,1.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
3,2023-04-10 19:20:21.946,Medium,20-29,Female,4.0,1-5 years,2.0,2.0,3.0,1.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
4,2023-04-10 19:20:29.145,Small,20-29,Male,3.0,1-5 years,2.0,2.0,2.0,2.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,2023-05-21 15:15:28.668,Small,30-39,Male,4.0,6-10 years,1.0,3.0,3.0,1.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
247,2023-05-21 15:16:49.891,Big,40-49,Male,4.0,11-15 years,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
248,2023-05-21 15:18:39.230,Big,30-39,Male,3.0,6-10 years,1.0,3.0,3.0,1.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
249,2023-05-28 21:40:57.415,Medium,40-49,Female,4.0,11-15 years,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
250,2023-05-28 21:42:01.498,Big,30-39,Male,4.0,11-15 years,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0

In [16]:
print(df2['1.     Firm Type'].unique())
print(df2['Gender'].unique())
print(df2['Years of Service'].unique())
print(df2['Age'].unique())

[nan 'Small' 'Medium' 'Big']
[nan 'Male' 'Female']
[nan '1-5 years' '6-10 years' 'Less than a year' '11-15 years'
 'At least 16 years']
[nan '30-39' '20-29' '40-49' '50-59']

In [19]:
#this time, i don't want to do one column at a time, I am creating a dictionary for all the columns left

replacement_dict = {
    '1.     Firm Type': {'Small': 1, 'Medium': 2, 'Big': 3},
    'Gender': {'Male': 1, 'Female': 2},
    'Years of Service': {'Less than a year': 1, '1-5 years': 2, '6-10 years': 3, '11-15 years': 4, 'At least 16 years': 5},
        'Age': {'20-29': 1, '30-39': 2, '40-49': 3, '50-59': 4}

}

dfFinal = df3.replace(replacement_dict)

In [20]:
dfFinal

,Timestamp,1. Firm Type,Age,Gender,Highest Qualification,Years of Service,Environment [This firm practices recycling pollutants and wastes.],Environment [This firm manufactures eco-friendly products.],Environment [This firm purchases environmentally friendly products.],Environment [This firm voluntarily does recycling and re-use.],...,Innovation [Our new product introduction has increased],Firm Reputation [The firm has a good reputation in the industry.],Firm Reputation [The firm is known for its high-quality products/services],Firm Reputation [The firm is reliable and trustworthy.],Firm Reputation [The firm has a positive image among its stakeholders.],Firm Reputation [The firm is respected and admired by its competitors.],Financial Performance [We had larger market share],Financial Performance [Our sales growth has been substantially better.],Financial Performance [Return on assets has been substantially better.],Financial Performance [Return on investment has been substantially.]
0,2023-04-10 17:08:11.946,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-04-10 18:26:23.983,1.0,2.0,1.0,4.0,2.0,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
2,2023-04-10 18:59:25.076,2.0,1.0,1.0,3.0,2.0,2.0,1.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
3,2023-04-10 19:20:21.946,2.0,1.0,2.0,4.0,2.0,2.0,2.0,3.0,1.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
4,2023-04-10 19:20:29.145,1.0,1.0,1.0,3.0,2.0,2.0,2.0,2.0,2.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,2023-05-21 15:15:28.668,1.0,2.0,1.0,4.0,3.0,1.0,3.0,3.0,1.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
247,2023-05-21 15:16:49.891,3.0,3.0,1.0,4.0,4.0,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
248,2023-05-21 15:18:39.230,3.0,2.0,1.0,3.0,3.0,1.0,3.0,3.0,1.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
249,2023-05-28 21:40:57.415,2.0,3.0,2.0,4.0,4.0,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
250,2023-05-28 21:42:01.498,3.0,2.0,1.0,4.0,4.0,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0

In [22]:
#saving the files as csv
dfFinal.to_csv("corporateResponse.csv",index=False)
dfFinal.to_excel("corporateResponse.xlsx",index=False)